"""
Shard Manager — Download, index, and manage model weight shards.

This is the main interface for node operators who want to:
  1. Download specific layer ranges of a model from HuggingFace
  2. Index what shards they have on disk
  3. Generate the node_shards.json config for the node server
  4. Verify shard integrity
  5. Report disk usage

Designed to be used both programmatically and via the node CLI.

Storage layout:
  data/shards/
    {model_id_safe}/
      model-00001-of-00004.safetensors
      model-00002-of-00004.safetensors
      ...
      manifest.json    ← shard index generated by this manager

The manifest maps files to their layer ranges and checksums, so the node
server can load the right files without re-parsing headers every time.
"""

import json
import os
import shutil
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

from maestro.shard_utils import (
    build_shard_descriptor,
    get_layer_range_from_file,
    hash_file,
    read_safetensors_header,
    scan_shard_directory,
    verify_shard_integrity,
)
from maestro.storage_proof import ShardDescriptor


_DEFAULT_SHARD_DIR = Path(__file__).resolve().parent.parent / "data" / "shards"


@dataclass
class ShardManifest:
    """Index of all shards for a model stored locally."""
    model_id: str
    total_layers: int = 0
    layer_coverage: list = field(default_factory=list)  # [[start, end], ...]
    files: list = field(default_factory=list)  # list of file entries
    total_size_bytes: int = 0
    precision: str = ""
    complete: bool = False  # True if all layers are covered


@dataclass
class ShardFileEntry:
    """One safetensors file in the manifest."""
    filename: str
    layer_range: list  # [start, end]
    size_bytes: int
    checksum: str
    tensor_count: int
    precision: str


class ShardManager:
    """
    Manages weight shards on disk for a storage node.

    Key operations:
      - download_model_shards() — Download specific files from HuggingFace
      - index_shards() — Scan disk and build manifest
      - get_shard_config() — Generate node_shards.json for the node server
      - verify_all() — Check integrity of all local shards
      - disk_usage() — Report total size of stored shards
    """

    def __init__(self, shard_dir: str | Path = None):
        self._dir = Path(shard_dir) if shard_dir else _DEFAULT_SHARD_DIR
        self._dir.mkdir(parents=True, exist_ok=True)

    def _model_dir(self, model_id: str) -> Path:
        """Get the local directory for a model's shards."""
        safe_name = model_id.replace("/", "__")
        d = self._dir / safe_name
        d.mkdir(parents=True, exist_ok=True)
        return d

    def _manifest_path(self, model_id: str) -> Path:
        return self._model_dir(model_id) / "manifest.json"

    # ------------------------------------------------------------------
    # Download
    # ------------------------------------------------------------------

    def download_model_shards(
        self,
        model_id: str,
        layer_start: int = 0,
        layer_end: int = -1,
        token: str = None,
        revision: str = "main",
    ) -> list[Path]:
        """
        Download safetensors files for the specified layer range from HuggingFace.

        If layer_end == -1, downloads all available shards.

        Returns list of downloaded file paths.

        Requires huggingface_hub to be installed. If not available, raises
        ImportError with installation instructions.
        """
        try:
            from huggingface_hub import HfApi, hf_hub_download
        except ImportError:
            raise ImportError(
                "huggingface_hub is required for downloading shards.\n"
                "Install it with: pip install huggingface_hub"
            )

        api = HfApi()
        model_dir = self._model_dir(model_id)

        # List all safetensors files in the repo
        try:
            files = api.list_repo_files(model_id, revision=revision, token=token)
        except Exception as e:
            raise RuntimeError(f"Failed to list files for {model_id}: {e}")

        safetensor_files = sorted(f for f in files if f.endswith(".safetensors"))
        if not safetensor_files:
            raise RuntimeError(f"No safetensors files found in {model_id}")

        # If we want all layers, download everything
        if layer_end == -1:
            target_files = safetensor_files
        else:
            # We need to download files and check which layers they contain.
            # HF sharded models split by file (model-00001-of-00004.safetensors),
            # and there's usually an index file that maps tensors to files.
            target_files = self._resolve_files_for_layers(
                model_id, safetensor_files, layer_start, layer_end,
                token=token, revision=revision,
            )

        downloaded = []
        for filename in target_files:
            dest = model_dir / Path(filename).name
            if dest.exists():
                print(f"  [exists] {dest.name}")
                downloaded.append(dest)
                continue

            print(f"  [downloading] {filename}...")
            try:
                path = hf_hub_download(
                    model_id,
                    filename=filename,
                    local_dir=str(model_dir),
                    token=token,
                    revision=revision,
                )
                downloaded.append(Path(path))
                print(f"  [done] {dest.name}")
            except Exception as e:
                print(f"  [error] {filename}: {e}")

        # Rebuild manifest after download
        self.index_shards(model_id)
        return downloaded

    def _resolve_files_for_layers(
        self,
        model_id: str,
        safetensor_files: list[str],
        layer_start: int,
        layer_end: int,
        token: str = None,
        revision: str = "main",
    ) -> list[str]:
        """
        Determine which safetensors files contain the requested layers.

        First tries the model's index.json (which maps tensor → file).
        Falls back to downloading all files if no index is available.
        """
        try:
            from huggingface_hub import hf_hub_download
        except ImportError:
            return safetensor_files

        # Try to find the safetensors index file
        import re
        index_candidates = [
            "model.safetensors.index.json",
        ]

        for index_name in index_candidates:
            try:
                index_path = hf_hub_download(
                    model_id, index_name,
                    local_dir=str(self._model_dir(model_id)),
                    token=token, revision=revision,
                )
                with open(index_path) as f:
                    index_data = json.load(f)

                weight_map = index_data.get("weight_map", {})
                if not weight_map:
                    continue

                # Figure out which files contain layers in our range
                needed_files = set()
                layer_patterns = [
                    re.compile(r"\.layers\.(\d+)\."),
                    re.compile(r"\.h\.(\d+)\."),
                    re.compile(r"\.layer\.(\d+)\."),
                    re.compile(r"blk\.(\d+)\."),
                    re.compile(r"\.blocks\.(\d+)\."),
                ]

                for tensor_name, filename in weight_map.items():
                    for pattern in layer_patterns:
                        m = pattern.search(tensor_name)
                        if m:
                            layer_idx = int(m.group(1))
                            if layer_start <= layer_idx <= layer_end:
                                needed_files.add(filename)
                            break

                # Also include embedding/norm files (no layer number)
                # since they're needed for first/last nodes
                for tensor_name, filename in weight_map.items():
                    has_layer = any(p.search(tensor_name) for p in layer_patterns)
                    if not has_layer:
                        # Embedding/norm tensor — include if we have layer 0
                        # or the final layer
                        if layer_start == 0:
                            needed_files.add(filename)

                if needed_files:
                    return sorted(needed_files)

            except Exception:
                continue

        # Fallback: download all files
        return safetensor_files

    # ------------------------------------------------------------------
    # Indexing
    # ------------------------------------------------------------------

    def index_shards(self, model_id: str) -> ShardManifest:
        """
        Scan local shard files and build/update the manifest.

        This reads safetensors headers (fast — no tensor data loaded) to
        determine layer ranges, tensor counts, and precision.
        """
        model_dir = self._model_dir(model_id)
        manifest = ShardManifest(model_id=model_id)
        all_layers = set()

        for filepath in sorted(model_dir.glob("*.safetensors")):
            try:
                header = read_safetensors_header(filepath)
                desc = build_shard_descriptor(filepath, model_id=model_id)

                entry = ShardFileEntry(
                    filename=filepath.name,
                    layer_range=list(desc.layer_range),
                    size_bytes=desc.size_bytes,
                    checksum=desc.checksum,
                    tensor_count=len(desc.tensor_names),
                    precision=desc.precision,
                )
                manifest.files.append(asdict(entry))
                manifest.total_size_bytes += desc.size_bytes

                if not manifest.precision:
                    manifest.precision = desc.precision

                # Track covered layers
                if desc.layer_range[0] >= 0:
                    for i in range(desc.layer_range[0], desc.layer_range[1] + 1):
                        all_layers.add(i)

            except (ValueError, OSError, json.JSONDecodeError) as e:
                print(f"  [skip] {filepath.name}: {e}")
                continue

        if all_layers:
            manifest.total_layers = max(all_layers) + 1
            # Build coverage ranges
            sorted_layers = sorted(all_layers)
            ranges = []
            start = sorted_layers[0]
            prev = start
            for layer in sorted_layers[1:]:
                if layer != prev + 1:
                    ranges.append([start, prev])
                    start = layer
                prev = layer
            ranges.append([start, prev])
            manifest.layer_coverage = ranges

            # Check if coverage is contiguous from 0 to max
            manifest.complete = (
                len(ranges) == 1
                and ranges[0][0] == 0
            )

        # Persist manifest
        manifest_path = self._manifest_path(model_id)
        manifest_path.write_text(json.dumps(asdict(manifest), indent=2))
        return manifest

    def load_manifest(self, model_id: str) -> Optional[ShardManifest]:
        """Load a previously built manifest from disk."""
        manifest_path = self._manifest_path(model_id)
        if not manifest_path.exists():
            return None
        try:
            data = json.loads(manifest_path.read_text())
            return ShardManifest(**{
                k: v for k, v in data.items()
                if k in ShardManifest.__dataclass_fields__
            })
        except (json.JSONDecodeError, TypeError):
            return None

    # ------------------------------------------------------------------
    # Node config generation
    # ------------------------------------------------------------------

    def generate_shard_config(
        self,
        model_id: str,
        layer_start: int = None,
        layer_end: int = None,
        output_path: str | Path = None,
    ) -> list[dict]:
        """
        Generate a node_shards.json config from local shards.

        If layer_start/layer_end are specified, only include files that
        overlap with that range. Otherwise includes all local shards.

        Returns the shard config list and optionally writes to output_path.
        """
        manifest = self.load_manifest(model_id)
        if not manifest:
            manifest = self.index_shards(model_id)

        model_dir = self._model_dir(model_id)
        config = []

        for file_entry in manifest.files:
            file_range = file_entry.get("layer_range", [-1, -1])

            # Filter by requested range
            if layer_start is not None and layer_end is not None:
                if file_range[0] >= 0:
                    if file_range[1] < layer_start or file_range[0] > layer_end:
                        continue

            shard_id = (
                f"{model_id.replace('/', '_')}"
                f"__L{file_range[0]}-{file_range[1]}"
                f"__{file_entry['filename']}"
            )
            config.append({
                "shard_id": shard_id,
                "model_id": model_id,
                "layer_range": file_range,
                "shard_format": "safetensors",
                "precision": file_entry.get("precision", manifest.precision),
                "size_bytes": file_entry.get("size_bytes", 0),
                "filename": file_entry["filename"],
                "filepath": str(model_dir / file_entry["filename"]),
                "checksum": file_entry.get("checksum", ""),
            })

        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(json.dumps(config, indent=2))

        return config

    # ------------------------------------------------------------------
    # Verification
    # ------------------------------------------------------------------

    def verify_all(self, model_id: str) -> dict:
        """
        Verify integrity of all local shards against manifest checksums.

        Returns: {"passed": [...], "failed": [...], "missing": [...]}
        """
        manifest = self.load_manifest(model_id)
        if not manifest:
            return {"passed": [], "failed": [], "missing": ["manifest not found"]}

        model_dir = self._model_dir(model_id)
        results = {"passed": [], "failed": [], "missing": []}

        for file_entry in manifest.files:
            filepath = model_dir / file_entry["filename"]
            if not filepath.exists():
                results["missing"].append(file_entry["filename"])
                continue

            expected = file_entry.get("checksum", "")
            if not expected:
                results["passed"].append(file_entry["filename"])
                continue

            if verify_shard_integrity(filepath, expected):
                results["passed"].append(file_entry["filename"])
            else:
                results["failed"].append(file_entry["filename"])

        return results

    # ------------------------------------------------------------------
    # Inventory
    # ------------------------------------------------------------------

    def list_models(self) -> list[str]:
        """List all model IDs that have local shards."""
        models = []
        for d in self._dir.iterdir():
            if d.is_dir() and any(d.glob("*.safetensors")):
                # Convert directory name back to model ID
                models.append(d.name.replace("__", "/"))
        return sorted(models)

    def disk_usage(self, model_id: str = None) -> dict:
        """
        Report disk usage for shards.

        If model_id is specified, reports for that model only.
        Otherwise reports total across all models.
        """
        if model_id:
            model_dir = self._model_dir(model_id)
            total = sum(f.stat().st_size for f in model_dir.glob("*.safetensors"))
            count = len(list(model_dir.glob("*.safetensors")))
            return {
                "model_id": model_id,
                "files": count,
                "total_bytes": total,
                "total_gb": round(total / (1024**3), 2),
            }

        total_bytes = 0
        total_files = 0
        per_model = {}
        for d in self._dir.iterdir():
            if d.is_dir():
                files = list(d.glob("*.safetensors"))
                size = sum(f.stat().st_size for f in files)
                model_name = d.name.replace("__", "/")
                per_model[model_name] = {
                    "files": len(files),
                    "total_bytes": size,
                    "total_gb": round(size / (1024**3), 2),
                }
                total_bytes += size
                total_files += len(files)

        return {
            "total_files": total_files,
            "total_bytes": total_bytes,
            "total_gb": round(total_bytes / (1024**3), 2),
            "per_model": per_model,
        }

    def remove_model(self, model_id: str) -> bool:
        """Remove all local shards for a model."""
        safe_name = model_id.replace("/", "__")
        model_dir = self._dir / safe_name
        if model_dir.exists() and any(model_dir.glob("*.safetensors")):
            shutil.rmtree(model_dir)
            return True
        return False

    def get_shard_filepath(self, model_id: str, filename: str) -> Optional[Path]:
        """Get the absolute path to a specific shard file."""
        filepath = self._model_dir(model_id) / filename
        return filepath if filepath.exists() else None
